# Generated by Django 5.2.3 on 2026-03-31 06:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_examinationtechnician"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientimage",
            name="image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="image"
            ),
        ),
    ]
